### ISSUE TITLE
Script doesn't work with Firefox 57

### ISSUE THREAD

**Issue by chsn1** [Fearxpc/JunkiesEnhancer#1]
After switching to Firefox 57 the script seems to do nothing anymore.
It is enabled and the newest version is installed.
Am I the only one with this problem?

**Comment by Fearxpc** [comment]
Hi chsn1,

no you are not alone.
With Firefox 57 Greasmonkey got a total rewrite and so they changed a lot so that old scripts can't run anymore. But so far not every feature is available in the new release.

[https://www.greasespot.net/2017/09/greasemonkey-4-for-users.html](url)

> Many user scripts will continue to run as expected, but this will break some scripts.  If you rely on such scripts, you might want to install Violentmonkey or Tampermonkey, both of which provide better compatibility for existing scripts.

So try to install Tampermonkey or Violentmonkey in Firefox 57 and it should work again.

**Comment by chsn1** [comment]
The script works with Tampermonkey. Thanks for the advice.
